### PR TITLE
Builds on GHC 8.8

### PR DESCRIPTION
**Pull request by Avi-D-coder**

### CODE REVIEW

**Comment by ag-eitilt** [comment]
The versions are more complex than that; at the very least, `MonadFail` requires `base >= 4.9`, and even if support for GHC 7.4 through 7.10 is dropped, as recent as GHC 8.6.5 requires `Control.Monad.Fail` be imported separately -- and under a different namespace since it conflicts with the `fail` at that point exported by `Prelude` and `Control.Monad`.

If the older versions get dropped, the fix is simple enough: add an `import qualified Control.Monad.Fail as Fail` and qualify the new class restriction from this PR and each use of `fail` in the function.

If GHC < 8.0 is kept, the library's not currently using a `LANGUAGE CPP` pragma yet; is that considered a lightweight enough extension to add to `Plugin.Pl.Common`?  I'd expect it to be, but I don't want to assume anything.  If so, the best way I can think of is wrapping a qualified import of (>= 4.9) `Control.Monad.Fail` and (< 4.9) `Control.Monad` -- both with the same qualified name -- and the type signature of `readM` (once with `MonadFail m`, and once with `Monad m`) both in `#if MIN_VERSION_base(4,9,0)`/`#else` blocks.  We should also double-check that this *does* actually compile on GHC that old; I've been getting -fPIC errors when I try, which is an issue with my system config as a whole rather than anything with the library; if nobody tries it first, I'll be back with the results if/when I get that fixed.

As a side note, there will be more code changes required for GHC 8.10 -- everything compiles, but some tests fail.

**Comment by isovector** [comment]
Can we get this merged? I've been missing `pointfree` and am unwilling to install an old GHC to get it built.

**Comment by bmillwood** [comment]
I uploaded 1.1.1.7 which I think fixes this. Turns out we only use `readM` with return type `Maybe`, so we can bypass the whole issue.

**Comment by isovector** [comment]
This fixes it for me. Thanks so much!

**Pull request closed without merging**
