### PR TITLE
Allow base-4.14 to support GHC 8.10

### PR DESCRIPTION
**Pull request by Bodigrim**

### CODE REVIEW

**Comment by Bodigrim** [comment]
Ping @bmillwood

**Comment by bmillwood** [comment]
I don't actually have GHC 8.10 at the moment. But if you promise me you ran the tests successfully, I can make a release.

**Comment by micwoj92** [comment]
Is there any eta for new release?
Build fails on Arch Linux and the AUR package is out of date, see https://aur.archlinux.org/packages/haskell-pointfree#comment-799873

**Comment by Bodigrim** [comment]
FWIW tests are fine both for `base-4.14` and `base-4.15`. I suggest making a revision.

**Comment by bmillwood** [comment]
1.1.1.8 uploaded.

**Pull request merged**
